{
    'collaborative': False, 
    'description': '', 
    'external_urls': {
        'spotify': 'https://open.spotify.com/playlist/3I0WxSdjhz4kwnoTPC9e6l'
    }, 
    'followers': {
        'href': None, 
        'total': 0
    }, 
    'href': 'https://api.spotify.com/v1/playlists/3I0WxSdjhz4kwnoTPC9e6l?additional_types=track', 
    'id': '3I0WxSdjhz4kwnoTPC9e6l', 
    'images': [
        {
            'height': 640, 
            'url': 'https://mosaic.scdn.co/640/ab67616d0000b273812807fb7bcf2cc258adbc09ab67616d0000b273ded3dbe3a36179504198e30aab67616d0000b273e103602d02f64d252bc95564ab67616d0000b273e33ccb95e40318ad3be9a591', 
            'width': 640
        }, 
        {
            'height': 300, 
            'url': 'https://mosaic.scdn.co/300/ab67616d0000b273812807fb7bcf2cc258adbc09ab67616d0000b273ded3dbe3a36179504198e30aab67616d0000b273e103602d02f64d252bc95564ab67616d0000b273e33ccb95e40318ad3be9a591', 
            'width': 300
        }, 
        {
            'height': 60, 
            'url': 'https://mosaic.scdn.co/60/ab67616d0000b273812807fb7bcf2cc258adbc09ab67616d0000b273ded3dbe3a36179504198e30aab67616d0000b273e103602d02f64d252bc95564ab67616d0000b273e33ccb95e40318ad3be9a591', 
            'width': 60
        }
    ], 
    'name': 'nepali ankit', 
    'owner': {
                'display_name': 'Prixa', 
                'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 
                'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 
                'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 
                'type': 'user', 
                'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'
            }, 
    'primary_color': None, 
    'public': True, 
    'snapshot_id': 'MTEsZWIwN2Q5NmU1MmMyNzRlMTQwYjViYmExNTdmNjkxNGRjOTEzZDExMQ==', 
    'tracks': {
                'href': 'https://api.spotify.com/v1/playlists/3I0WxSdjhz4kwnoTPC9e6l/tracks?offset=0&limit=100&additional_types=track', 
                'items': [{'added_at': '2021-06-07T13:27:07Z', 
                'added_by': {
                                'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 
                                'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 
                                'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 
                                'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'
                            }, 
                'is_local': False, 
                'primary_color': None, 
                'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4agubnRqj4q1dPR2wuUniV'}, 'href': 'https://api.spotify.com/v1/artists/4agubnRqj4q1dPR2wuUniV', 'id': '4agubnRqj4q1dPR2wuUniV', 'name': 'Ayush Gauchan', 'type': 'artist', 'uri': 
'spotify:artist:4agubnRqj4q1dPR2wuUniV'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/7EkzWnQHsYZIonsDrjKh0T'}, 'href': 'https://api.spotify.com/v1/albums/7EkzWnQHsYZIonsDrjKh0T', 'id': '7EkzWnQHsYZIonsDrjKh0T', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273e103602d02f64d252bc95564', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02e103602d02f64d252bc95564', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851e103602d02f64d252bc95564', 'width': 64}], 'name': 'Maya', 'release_date': '2021-02-02', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:7EkzWnQHsYZIonsDrjKh0T'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/4agubnRqj4q1dPR2wuUniV'}, 'href': 'https://api.spotify.com/v1/artists/4agubnRqj4q1dPR2wuUniV', 'id': '4agubnRqj4q1dPR2wuUniV', 'name': 'Ayush Gauchan', 'type': 'artist', 'uri': 'spotify:artist:4agubnRqj4q1dPR2wuUniV'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 188459, 'episode': False, 'explicit': False, 'external_ids': {'isrc': 'SE5BU2168497'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/2iCvfpD5hEzLeqEbsXhXVQ'}, 'href': 'https://api.spotify.com/v1/tracks/2iCvfpD5hEzLeqEbsXhXVQ', 'id': '2iCvfpD5hEzLeqEbsXhXVQ', 'is_local': False, 'name': 'Maya', 'popularity': 50, 'preview_url': 'https://p.scdn.co/mp3-preview/e886fb00d9475721dffbb495460cff1dfe4f20c8?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:2iCvfpD5hEzLeqEbsXhXVQ'}, 'video_thumbnail': {'url': None}}, {'added_at': '2021-06-07T13:28:56Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'}, 'is_local': False, 'primary_color': None, 'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5uVTzyCO2MknEPABhTCIkz'}, 'href': 'https://api.spotify.com/v1/artists/5uVTzyCO2MknEPABhTCIkz', 'id': '5uVTzyCO2MknEPABhTCIkz', 'name': 'Neetesh Jung Kunwar', 'type': 'artist', 'uri': 'spotify:artist:5uVTzyCO2MknEPABhTCIkz'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/46PTh3Z1WCK3eNgdOTCzwp'}, 'href': 'https://api.spotify.com/v1/albums/46PTh3Z1WCK3eNgdOTCzwp', 'id': '46PTh3Z1WCK3eNgdOTCzwp', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273e33ccb95e40318ad3be9a591', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02e33ccb95e40318ad3be9a591', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851e33ccb95e40318ad3be9a591', 'width': 64}], 'name': 'Kholai Khola', 'release_date': '2021-02-08', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:46PTh3Z1WCK3eNgdOTCzwp'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5uVTzyCO2MknEPABhTCIkz'}, 'href': 'https://api.spotify.com/v1/artists/5uVTzyCO2MknEPABhTCIkz', 'id': '5uVTzyCO2MknEPABhTCIkz', 'name': 'Neetesh Jung Kunwar', 'type': 'artist', 'uri': 'spotify:artist:5uVTzyCO2MknEPABhTCIkz'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 
'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 
'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 
'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 296761, 'episode': False, 'explicit': False, 'external_ids': {'isrc': 'SEYOK2104333'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/4KWWotE0IbxApQFNvtCegt'}, 'href': 'https://api.spotify.com/v1/tracks/4KWWotE0IbxApQFNvtCegt', 'id': '4KWWotE0IbxApQFNvtCegt', 'is_local': False, 'name': 'Kholai Khola', 'popularity': 39, 'preview_url': 'https://p.scdn.co/mp3-preview/1631e9d03d2d0bcd1bd04e0f41da2dd49a9fd53a?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:4KWWotE0IbxApQFNvtCegt'}, 'video_thumbnail': {'url': None}}, {'added_at': '2021-06-07T13:29:29Z', 'added_by': {'external_urls': 
{'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'}, 'is_local': False, 'primary_color': None, 'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1D0B4qrMRfjzDfBlijs3YH'}, 'href': 'https://api.spotify.com/v1/artists/1D0B4qrMRfjzDfBlijs3YH', 'id': '1D0B4qrMRfjzDfBlijs3YH', 'name': 'Yabesh Thapa', 'type': 'artist', 'uri': 'spotify:artist:1D0B4qrMRfjzDfBlijs3YH'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 
'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 
'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 
'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/4yEDXMxK32OLqpDxliC2Sp'}, 'href': 'https://api.spotify.com/v1/albums/4yEDXMxK32OLqpDxliC2Sp', 'id': '4yEDXMxK32OLqpDxliC2Sp', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273ded3dbe3a36179504198e30a', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02ded3dbe3a36179504198e30a', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851ded3dbe3a36179504198e30a', 'width': 
64}], 'name': 'Ae Mutu', 'release_date': '2020-09-27', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:4yEDXMxK32OLqpDxliC2Sp'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1D0B4qrMRfjzDfBlijs3YH'}, 'href': 'https://api.spotify.com/v1/artists/1D0B4qrMRfjzDfBlijs3YH', 
'id': '1D0B4qrMRfjzDfBlijs3YH', 'name': 'Yabesh Thapa', 'type': 'artist', 'uri': 'spotify:artist:1D0B4qrMRfjzDfBlijs3YH'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5tqdcJRokx2Pu3WAfSJ699'}, 'href': 'https://api.spotify.com/v1/artists/5tqdcJRokx2Pu3WAfSJ699', 'id': '5tqdcJRokx2Pu3WAfSJ699', 'name': 'Zeroo', 'type': 'artist', 'uri': 'spotify:artist:5tqdcJRokx2Pu3WAfSJ699'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 
'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 
'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 
'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 160034, 'episode': False, 'explicit': False, 'external_ids': {'isrc': 'QZK6G2032375'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/0oLlykxJddGnu0eLel4JuO'}, 'href': 'https://api.spotify.com/v1/tracks/0oLlykxJddGnu0eLel4JuO', 'id': '0oLlykxJddGnu0eLel4JuO', 'is_local': False, 'name': 'Ae Mutu', 'popularity': 41, 'preview_url': 'https://p.scdn.co/mp3-preview/c9a66baae924ac8d201f6c9a291ac338805b164a?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:0oLlykxJddGnu0eLel4JuO'}, 'video_thumbnail': {'url': None}}, {'added_at': '2021-06-07T13:29:33Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'}, 'is_local': False, 'primary_color': None, 'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6vl1XAVrZBbKvuXJeOXeaB'}, 'href': 'https://api.spotify.com/v1/artists/6vl1XAVrZBbKvuXJeOXeaB', 'id': '6vl1XAVrZBbKvuXJeOXeaB', 'name': 'Vek', 'type': 'artist', 'uri': 'spotify:artist:6vl1XAVrZBbKvuXJeOXeaB'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/2ClhOti59seHzx6K2ScaLz'}, 'href': 'https://api.spotify.com/v1/albums/2ClhOti59seHzx6K2ScaLz', 'id': '2ClhOti59seHzx6K2ScaLz', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273812807fb7bcf2cc258adbc09', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02812807fb7bcf2cc258adbc09', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851812807fb7bcf2cc258adbc09', 'width': 64}], 'name': 'Mayalu', 'release_date': '2020-07-18', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:2ClhOti59seHzx6K2ScaLz'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6vl1XAVrZBbKvuXJeOXeaB'}, 'href': 'https://api.spotify.com/v1/artists/6vl1XAVrZBbKvuXJeOXeaB', 'id': '6vl1XAVrZBbKvuXJeOXeaB', 'name': 'Vek', 'type': 'artist', 'uri': 'spotify:artist:6vl1XAVrZBbKvuXJeOXeaB'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1D0B4qrMRfjzDfBlijs3YH'}, 'href': 'https://api.spotify.com/v1/artists/1D0B4qrMRfjzDfBlijs3YH', 'id': '1D0B4qrMRfjzDfBlijs3YH', 'name': 'Yabesh Thapa', 'type': 'artist', 'uri': 'spotify:artist:1D0B4qrMRfjzDfBlijs3YH'}], 
'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 237714, 'episode': False, 'explicit': False, 'external_ids': {'isrc': 'QZHNB2036186'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/7lLeoZv3rPnfbh9AsJDJWq'}, 'href': 'https://api.spotify.com/v1/tracks/7lLeoZv3rPnfbh9AsJDJWq', 'id': '7lLeoZv3rPnfbh9AsJDJWq', 'is_local': False, 'name': 'Mayalu', 'popularity': 46, 'preview_url': 'https://p.scdn.co/mp3-preview/cce5a679f5fb1c66581907daaee7a2ae91ba9c3d?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:7lLeoZv3rPnfbh9AsJDJWq'}, 'video_thumbnail': {'url': None}}, {'added_at': '2021-06-07T13:29:38Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'}, 'is_local': False, 'primary_color': None, 'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3kkNLwATkgYS5e0DwDmn2i'}, 'href': 'https://api.spotify.com/v1/artists/3kkNLwATkgYS5e0DwDmn2i', 'id': '3kkNLwATkgYS5e0DwDmn2i', 'name': 'Shashwot Khadka', 'type': 'artist', 'uri': 'spotify:artist:3kkNLwATkgYS5e0DwDmn2i'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/1CafBU7XYHQcR3p1DijHKN'}, 'href': 'https://api.spotify.com/v1/albums/1CafBU7XYHQcR3p1DijHKN', 'id': '1CafBU7XYHQcR3p1DijHKN', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273c3cfb6473bc92b43759df805', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02c3cfb6473bc92b43759df805', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851c3cfb6473bc92b43759df805', 'width': 64}], 'name': 'Batash', 'release_date': '2020-09-11', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:1CafBU7XYHQcR3p1DijHKN'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/3kkNLwATkgYS5e0DwDmn2i'}, 'href': 'https://api.spotify.com/v1/artists/3kkNLwATkgYS5e0DwDmn2i', 'id': '3kkNLwATkgYS5e0DwDmn2i', 'name': 'Shashwot Khadka', 'type': 'artist', 'uri': 'spotify:artist:3kkNLwATkgYS5e0DwDmn2i'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 180000, 'episode': False, 'explicit': False, 
'external_ids': {'isrc': 'QZK6J2032539'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/1A4clpbjUAXFAb3KdEX4Z4'}, 'href': 'https://api.spotify.com/v1/tracks/1A4clpbjUAXFAb3KdEX4Z4', 'id': '1A4clpbjUAXFAb3KdEX4Z4', 'is_local': False, 'name': 'Batash', 'popularity': 49, 'preview_url': 'https://p.scdn.co/mp3-preview/1ffdefdd9fb3dd0abab11a269f67b2ad40ee88c1?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:1A4clpbjUAXFAb3KdEX4Z4'}, 'video_thumbnail': {'url': None}}, {'added_at': '2021-06-07T13:31:13Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'}, 'is_local': False, 'primary_color': None, 'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1deQzOQwArAsUgm2WdjtyI'}, 'href': 'https://api.spotify.com/v1/artists/1deQzOQwArAsUgm2WdjtyI', 'id': '1deQzOQwArAsUgm2WdjtyI', 'name': 'Sajjan Raj Vaidya', 'type': 'artist', 'uri': 'spotify:artist:1deQzOQwArAsUgm2WdjtyI'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/6mlhpDUujznoLiNKVCS6TW'}, 'href': 'https://api.spotify.com/v1/albums/6mlhpDUujznoLiNKVCS6TW', 'id': '6mlhpDUujznoLiNKVCS6TW', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b27360209e39f19991a7b1b58c29', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e0260209e39f19991a7b1b58c29', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d0000485160209e39f19991a7b1b58c29', 'width': 64}], 'name': 'Mooskaan', 'release_date': '2018-05-01', 'release_date_precision': 'day', 'total_tracks': 2, 'type': 'album', 'uri': 'spotify:album:6mlhpDUujznoLiNKVCS6TW'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1deQzOQwArAsUgm2WdjtyI'}, 'href': 'https://api.spotify.com/v1/artists/1deQzOQwArAsUgm2WdjtyI', 'id': '1deQzOQwArAsUgm2WdjtyI', 'name': 'Sajjan Raj Vaidya', 'type': 'artist', 'uri': 'spotify:artist:1deQzOQwArAsUgm2WdjtyI'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 
'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 
'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 
'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 303529, 'episode': False, 'explicit': False, 'external_ids': {'isrc': 'GBMJG1806638'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/6quygE0BQuMUY861Crte1N'}, 'href': 
'https://api.spotify.com/v1/tracks/6quygE0BQuMUY861Crte1N', 'id': '6quygE0BQuMUY861Crte1N', 'is_local': False, 'name': 'Mooskaan', 'popularity': 44, 'preview_url': 'https://p.scdn.co/mp3-preview/e4bfb1b231f3a921e9e799f34e141f09d3f97ff7?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:6quygE0BQuMUY861Crte1N'}, 'video_thumbnail': {'url': None}}, {'added_at': '2021-06-07T13:31:30Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'}, 'is_local': False, 'primary_color': None, 'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1deQzOQwArAsUgm2WdjtyI'}, 'href': 'https://api.spotify.com/v1/artists/1deQzOQwArAsUgm2WdjtyI', 'id': '1deQzOQwArAsUgm2WdjtyI', 'name': 'Sajjan Raj Vaidya', 'type': 'artist', 'uri': 'spotify:artist:1deQzOQwArAsUgm2WdjtyI'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/2ccy85ehHt4W0SX9B1rlqW'}, 'href': 'https://api.spotify.com/v1/albums/2ccy85ehHt4W0SX9B1rlqW', 'id': '2ccy85ehHt4W0SX9B1rlqW', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273fe824ddbaa151e81cb04bea0', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02fe824ddbaa151e81cb04bea0', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851fe824ddbaa151e81cb04bea0', 'width': 64}], 'name': 'Chitthi Bhitra', 
'release_date': '2018-01-01', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:2ccy85ehHt4W0SX9B1rlqW'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1deQzOQwArAsUgm2WdjtyI'}, 'href': 'https://api.spotify.com/v1/artists/1deQzOQwArAsUgm2WdjtyI', 'id': '1deQzOQwArAsUgm2WdjtyI', 'name': 'Sajjan Raj Vaidya', 'type': 'artist', 'uri': 'spotify:artist:1deQzOQwArAsUgm2WdjtyI'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 
'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 
'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 
'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 302560, 'episode': False, 'explicit': False, 'external_ids': {'isrc': 'GBMJG1800158'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/6XPLnH0wby09UGaJYtv4NT'}, 'href': 'https://api.spotify.com/v1/tracks/6XPLnH0wby09UGaJYtv4NT', 'id': '6XPLnH0wby09UGaJYtv4NT', 'is_local': False, 'name': 'Chitthi Bhitra', 'popularity': 46, 'preview_url': 'https://p.scdn.co/mp3-preview/9078446a8ef73a29b0884ff8c3d3e88ad33c41eb?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:6XPLnH0wby09UGaJYtv4NT'}, 'video_thumbnail': {'url': None}}, {'added_at': '2021-06-07T14:38:13Z', 'added_by': {'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'}, 'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g', 'id': 'ehfc7cnf8bizgh9gm0xysqn7g', 'type': 'user', 'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g'}, 'is_local': False, 'primary_color': None, 'track': {'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1deQzOQwArAsUgm2WdjtyI'}, 'href': 'https://api.spotify.com/v1/artists/1deQzOQwArAsUgm2WdjtyI', 'id': '1deQzOQwArAsUgm2WdjtyI', 'name': 'Sajjan Raj Vaidya', 'type': 'artist', 'uri': 'spotify:artist:1deQzOQwArAsUgm2WdjtyI'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'external_urls': {'spotify': 'https://open.spotify.com/album/3u1i6mEyXHm3hZj7UMWIaw'}, 'href': 'https://api.spotify.com/v1/albums/3u1i6mEyXHm3hZj7UMWIaw', 'id': '3u1i6mEyXHm3hZj7UMWIaw', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b2739fb8b0c8fa745976c8f7f76c', 'width': 640}, {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e029fb8b0c8fa745976c8f7f76c', 'width': 300}, {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d000048519fb8b0c8fa745976c8f7f76c', 'width': 64}], 'name': 'Phutki Jaaney Jovan', 'release_date': '2020-05-16', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:3u1i6mEyXHm3hZj7UMWIaw'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/1deQzOQwArAsUgm2WdjtyI'}, 'href': 'https://api.spotify.com/v1/artists/1deQzOQwArAsUgm2WdjtyI', 'id': '1deQzOQwArAsUgm2WdjtyI', 'name': 'Sajjan Raj Vaidya', 'type': 'artist', 'uri': 'spotify:artist:1deQzOQwArAsUgm2WdjtyI'}], 'available_markets': ['AD', 'AE', 'AG', 'AL', 'AM', 'AO', 'AR', 'AT', 'AU', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BN', 'BO', 'BR', 'BS', 'BT', 'BW', 'BY', 'BZ', 'CA', 'CH', 'CI', 'CL', 'CM', 'CO', 'CR', 'CV', 'CW', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'ES', 'FI', 'FJ', 'FM', 'FR', 'GA', 'GB', 'GD', 'GE', 'GH', 'GM', 'GN', 'GQ', 'GR', 'GT', 'GW', 'GY', 'HK', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IN', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KR', 'KW', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MG', 'MH', 'MK', 'ML', 'MN', 'MO', 'MR', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NE', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NZ', 'OM', 'PA', 'PE', 'PG', 'PH', 'PK', 'PL', 'PS', 'PT', 'PW', 'PY', 'QA', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SE', 'SG', 'SI', 'SK', 'SL', 'SM', 'SN', 'SR', 'ST', 'SV', 'SZ', 'TD', 'TG', 'TH', 'TL', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'US', 'UY', 'UZ', 'VC', 'VN', 'VU', 'WS', 'XK', 'ZA', 'ZM', 'ZW'], 'disc_number': 1, 'duration_ms': 220800, 'episode': False, 'explicit': False, 'external_ids': {'isrc': 'GBMJG2000611'}, 
'external_urls': {'spotify': 'https://open.spotify.com/track/12b3bKEbdjtL1Ga0n3ybzK'}, 'href': 'https://api.spotify.com/v1/tracks/12b3bKEbdjtL1Ga0n3ybzK', 'id': '12b3bKEbdjtL1Ga0n3ybzK', 'is_local': False, 'name': 'Phutki Jaaney Jovan', 'popularity': 44, 'preview_url': 'https://p.scdn.co/mp3-preview/23f4f6975e9a267951d13a86cce4177c694fb69d?cid=0f0fe3f41d224afa9a240b7334554e81', 'track': True, 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:12b3bKEbdjtL1Ga0n3ybzK'}, 'video_thumbnail': {'url': None}}], 'limit': 100, 'next': None, 'offset': 0, 'previous': None, 'total': 8}, 'type': 'playlist', 'uri': 'spotify:playlist:3I0WxSdjhz4kwnoTPC9e6l'}

#!/usr/bin/python
# -*- coding: utf-8 -*-
{
    'added_at': '2021-06-07T13:27:07Z',
    'added_by': {
        'external_urls': {'spotify': 'https://open.spotify.com/user/ehfc7cnf8bizgh9gm0xysqn7g'},
        'href': 'https://api.spotify.com/v1/users/ehfc7cnf8bizgh9gm0xysqn7g',
        'id': 'ehfc7cnf8bizgh9gm0xysqn7g',
        'type': 'user',
        'uri': 'spotify:user:ehfc7cnf8bizgh9gm0xysqn7g',
        },
    'is_local': False,
    'primary_color': None,
    'track': {
        'album': {
            'album_type': 'single',
            'artists': [{
                'external_urls': {'spotify': 'https://open.spotify.com/artist/4agubnRqj4q1dPR2wuUniV'
                                  },
                'href': 'https://api.spotify.com/v1/artists/4agubnRqj4q1dPR2wuUniV'
                    ,
                'id': '4agubnRqj4q1dPR2wuUniV',
                'name': 'Ayush Gauchan',
                'type': 'artist',
                'uri': 'spotify:artist:4agubnRqj4q1dPR2wuUniV',
                }],
            'available_markets': [
                'AD',
                'AE',
                'AG',
                'AL',
                'AM',
                'AO',
                'AR',
                'AT',
                'AU',
                'AZ',
                'BA',
                'BB',
                'BD',
                'BE',
                'BF',
                'BG',
                'BH',
                'BI',
                'BJ',
                'BN',
                'BO',
                'BR',
                'BS',
                'BT',
                'BW',
                'BY',
                'BZ',
                'CA',
                'CH',
                'CI',
                'CL',
                'CM',
                'CO',
                'CR',
                'CV',
                'CW',
                'CY',
                'CZ',
                'DE',
                'DJ',
                'DK',
                'DM',
                'DO',
                'DZ',
                'EC',
                'EE',
                'EG',
                'ES',
                'FI',
                'FJ',
                'FM',
                'FR',
                'GA',
                'GB',
                'GD',
                'GE',
                'GH',
                'GM',
                'GN',
                'GQ',
                'GR',
                'GT',
                'GW',
                'GY',
                'HK',
                'HN',
                'HR',
                'HT',
                'HU',
                'ID',
                'IE',
                'IL',
                'IN',
                'IS',
                'IT',
                'JM',
                'JO',
                'JP',
                'KE',
                'KG',
                'KH',
                'KI',
                'KM',
                'KN',
                'KR',
                'KW',
                'KZ',
                'LA',
                'LB',
                'LC',
                'LI',
                'LK',
                'LR',
                'LS',
                'LT',
                'LU',
                'LV',
                'MA',
                'MC',
                'MD',
                'ME',
                'MG',
                'MH',
                'MK',
                'ML',
                'MN',
                'MO',
                'MR',
                'MT',
                'MU',
                'MV',
                'MW',
                'MX',
                'MY',
                'MZ',
                'NA',
                'NE',
                'NG',
                'NI',
                'NL',
                'NO',
                'NP',
                'NR',
                'NZ',
                'OM',
                'PA',
                'PE',
                'PG',
                'PH',
                'PK',
                'PL',
                'PS',
                'PT',
                'PW',
                'PY',
                'QA',
                'RO',
                'RS',
                'RU',
                'RW',
                'SA',
                'SB',
                'SC',
                'SE',
                'SG',
                'SI',
                'SK',
                'SL',
                'SM',
                'SN',
                'SR',
                'ST',
                'SV',
                'SZ',
                'TD',
                'TG',
                'TH',
                'TL',
                'TN',
                'TO',
                'TR',
                'TT',
                'TV',
                'TW',
                'TZ',
                'UA',
                'UG',
                'US',
                'UY',
                'UZ',
                'VC',
                'VN',
                'VU',
                'WS',
                'XK',
                'ZA',
                'ZM',
                'ZW',
                ],
            'external_urls': {'spotify': 'https://open.spotify.com/album/7EkzWnQHsYZIonsDrjKh0T'},
            'href': 'https://api.spotify.com/v1/albums/7EkzWnQHsYZIonsDrjKh0T',
            'id': '7EkzWnQHsYZIonsDrjKh0T',
            'images': [{'height': 640,
                       'url': 'https://i.scdn.co/image/ab67616d0000b273e103602d02f64d252bc95564'
                       , 'width': 640}, {'height': 300,
                       'url': 'https://i.scdn.co/image/ab67616d00001e02e103602d02f64d252bc95564'
                       , 'width': 300}, {'height': 64,
                       'url': 'https://i.scdn.co/image/ab67616d00004851e103602d02f64d252bc95564'
                       , 'width': 64}],
            'name': 'Maya',
            'release_date': '2021-02-02',
            'release_date_precision': 'day',
            'total_tracks': 1,
            'type': 'album',
            'uri': 'spotify:album:7EkzWnQHsYZIonsDrjKh0T',
            },
        'artists': [{
            'external_urls': {'spotify': 'https://open.spotify.com/artist/4agubnRqj4q1dPR2wuUniV'
                              },
            'href': 'https://api.spotify.com/v1/artists/4agubnRqj4q1dPR2wuUniV'
                ,
            'id': '4agubnRqj4q1dPR2wuUniV',
            'name': 'Ayush Gauchan',
            'type': 'artist',
            'uri': 'spotify:artist:4agubnRqj4q1dPR2wuUniV',
            }],
        'available_markets': [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
            ],
        'disc_number': 1,
        'duration_ms': 188459,
        'episode': False,
        'explicit': False,
        'external_ids': {'isrc': 'SE5BU2168497'},
        'external_urls': {'spotify': 'https://open.spotify.com/track/2iCvfpD5hEzLeqEbsXhXVQ'},
        'href': 'https://api.spotify.com/v1/tracks/2iCvfpD5hEzLeqEbsXhXVQ',
        'id': '2iCvfpD5hEzLeqEbsXhXVQ',
        'is_local': False,
        'name': 'Maya',
        'popularity': 50,
        'preview_url': 'https://p.scdn.co/mp3-preview/e886fb00d9475721dffbb495460cff1dfe4f20c8?cid=0f0fe3f41d224afa9a240b7334554e81',
        'track': True,
        'track_number': 1,
        'type': 'track',
        'uri': 'spotify:track:2iCvfpD5hEzLeqEbsXhXVQ',
        },
    'video_thumbnail': {'url': None},
    }

			